language: csharp
solution: "./MicrotingOutlook.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./MicrotingOutlook.sln
- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
- msbuild ./MicrotingOutlook.sln
- mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ./UnitTest/bin/Debug/UnitTest.dll